.TH "iterator< T >" 3 "Fri Jul 12 2019" "Version 1.0" "Vector" \" -*- nroff -*-
.ad l
.nh
.SH NAME
iterator< T >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <iterator\&.h>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef T \fBvalue_type\fP"
.br
.RI "Value type the iterator points to\&. "
.ti -1c
.RI "typedef T * \fBpointer\fP"
.br
.RI "Pointer to the value type\&. "
.ti -1c
.RI "typedef T & \fBreference\fP"
.br
.RI "Reference to the value type\&. "
.ti -1c
.RI "typedef std::ptrdiff_t \fBdifference_type\fP"
.br
.RI "Used to calculated distance between iterators\&. "
.ti -1c
.RI "typedef std::bidirectional_iterator_tag \fBiterator_category\fP"
.br
.RI "Iterator category\&. "
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBiterator\fP (\fBpointer\fP ptr=nullptr)"
.br
.ti -1c
.RI "\fBiterator\fP (const \fBiterator\fP< T > &l)"
.br
.ti -1c
.RI "\fB~iterator\fP ()"
.br
.ti -1c
.RI "\fBiterator\fP & \fBoperator=\fP (const \fBiterator\fP &rhs)"
.br
.RI "it1 = it2; "
.ti -1c
.RI "\fBiterator\fP \fBoperator++\fP ()"
.br
.RI "++it; "
.ti -1c
.RI "\fBiterator\fP \fBoperator++\fP (int)"
.br
.RI "it++; "
.ti -1c
.RI "\fBiterator\fP \fBoperator\-\-\fP ()"
.br
.RI "--it; "
.ti -1c
.RI "\fBiterator\fP \fBoperator\-\-\fP (int)"
.br
.RI "it--; "
.ti -1c
.RI "\fBdifference_type\fP \fBoperator\-\fP (const \fBiterator\fP &rhs)"
.br
.RI "it = it1 - it2; "
.ti -1c
.RI "\fBreference\fP \fBoperator *\fP (void)"
.br
.RI "*it = x; "
.ti -1c
.RI "\fBreference\fP \fBoperator *\fP (void) const"
.br
.RI "x = *it; "
.ti -1c
.RI "\fBpointer\fP \fBoperator\->\fP (void) const"
.br
.RI "it-> "
.ti -1c
.RI "bool \fBoperator==\fP (const \fBiterator\fP &it) const"
.br
.RI "it1 == it2 "
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBiterator\fP &it) const"
.br
.RI "it1 != it2 "
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "\fBiterator\fP \fBoperator+\fP (\fBdifference_type\fP n, \fBiterator\fP it)"
.br
.RI "n + it "
.ti -1c
.RI "\fBiterator\fP \fBoperator+\fP (\fBiterator\fP it, \fBdifference_type\fP n)"
.br
.RI "it + n "
.ti -1c
.RI "\fBiterator\fP \fBoperator\-\fP (\fBdifference_type\fP n, \fBiterator\fP it)"
.br
.RI "n - it "
.ti -1c
.RI "\fBiterator\fP \fBoperator\-\fP (\fBiterator\fP it, \fBdifference_type\fP n)"
.br
.RI "it - n "
.ti -1c
.RI "std::ostream & \fBoperator<<\fP (std::ostream &os, const \fBiterator\fP< T > &v)"
.br
.RI "<< it "
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename T>
.br
class iterator< T >"

.PP
Definition at line 2 of file iterator\&.h\&.
.SH "Member Typedef Documentation"
.PP 
.SS "template<typename T> typedef std::ptrdiff_t \fBiterator\fP< T >::\fBdifference_type\fP"

.PP
Used to calculated distance between iterators\&. 
.PP
Definition at line 8 of file iterator\&.h\&.
.SS "template<typename T> typedef std::bidirectional_iterator_tag \fBiterator\fP< T >::\fBiterator_category\fP"

.PP
Iterator category\&. 
.PP
Definition at line 9 of file iterator\&.h\&.
.SS "template<typename T> typedef T* \fBiterator\fP< T >::\fBpointer\fP"

.PP
Pointer to the value type\&. 
.PP
Definition at line 6 of file iterator\&.h\&.
.SS "template<typename T> typedef T& \fBiterator\fP< T >::\fBreference\fP"

.PP
Reference to the value type\&. 
.PP
Definition at line 7 of file iterator\&.h\&.
.SS "template<typename T> typedef T \fBiterator\fP< T >::\fBvalue_type\fP"

.PP
Value type the iterator points to\&. 
.PP
Definition at line 5 of file iterator\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename T> \fBiterator\fP< T >::\fBiterator\fP (\fBpointer\fP ptr = \fCnullptr\fP)\fC [inline]\fP"

.PP
Definition at line 11 of file iterator\&.h\&.
.SS "template<typename T> \fBiterator\fP< T >::\fBiterator\fP (const \fBiterator\fP< T > & l)\fC [inline]\fP"

.PP
Definition at line 13 of file iterator\&.h\&.
.SS "template<typename T> \fBiterator\fP< T >::~\fBiterator\fP ()\fC [inline]\fP"

.PP
Definition at line 15 of file iterator\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "template<typename T> \fBreference\fP \fBiterator\fP< T >::operator * (void)\fC [inline]\fP"

.PP
*it = x; 
.PP
Definition at line 48 of file iterator\&.h\&.
.SS "template<typename T> \fBreference\fP \fBiterator\fP< T >::operator * (void) const\fC [inline]\fP"

.PP
x = *it; 
.PP
Definition at line 51 of file iterator\&.h\&.
.SS "template<typename T> bool \fBiterator\fP< T >::operator!= (const \fBiterator\fP< T > & it) const\fC [inline]\fP"

.PP
it1 != it2 
.PP
Definition at line 83 of file iterator\&.h\&.
.SS "template<typename T> \fBiterator\fP \fBiterator\fP< T >::operator++ ()\fC [inline]\fP"

.PP
++it; 
.PP
Definition at line 24 of file iterator\&.h\&.
.SS "template<typename T> \fBiterator\fP \fBiterator\fP< T >::operator++ (int)\fC [inline]\fP"

.PP
it++; 
.PP
Definition at line 30 of file iterator\&.h\&.
.SS "template<typename T> \fBdifference_type\fP \fBiterator\fP< T >::operator\- (const \fBiterator\fP< T > & rhs)\fC [inline]\fP"

.PP
it = it1 - it2; 
.PP
Definition at line 45 of file iterator\&.h\&.
.SS "template<typename T> \fBiterator\fP \fBiterator\fP< T >::operator\-\- ()\fC [inline]\fP"

.PP
--it; 
.PP
Definition at line 36 of file iterator\&.h\&.
.SS "template<typename T> \fBiterator\fP \fBiterator\fP< T >::operator\-\- (int)\fC [inline]\fP"

.PP
it--; 
.PP
Definition at line 39 of file iterator\&.h\&.
.SS "template<typename T> \fBpointer\fP \fBiterator\fP< T >::operator\-> (void) const\fC [inline]\fP"

.PP
it-> 
.PP
Definition at line 54 of file iterator\&.h\&.
.SS "template<typename T> \fBiterator\fP& \fBiterator\fP< T >::operator= (const \fBiterator\fP< T > & rhs)\fC [inline]\fP"

.PP
it1 = it2; 
.PP
Definition at line 18 of file iterator\&.h\&.
.SS "template<typename T> bool \fBiterator\fP< T >::operator== (const \fBiterator\fP< T > & it) const\fC [inline]\fP"

.PP
it1 == it2 
.PP
Definition at line 80 of file iterator\&.h\&.
.SH "Friends And Related Function Documentation"
.PP 
.SS "template<typename T> \fBiterator\fP operator+ (\fBdifference_type\fP n, \fBiterator\fP< T > it)\fC [friend]\fP"

.PP
n + it 
.PP
Definition at line 60 of file iterator\&.h\&.
.SS "template<typename T> \fBiterator\fP operator+ (\fBiterator\fP< T > it, \fBdifference_type\fP n)\fC [friend]\fP"

.PP
it + n 
.PP
Definition at line 65 of file iterator\&.h\&.
.SS "template<typename T> \fBiterator\fP operator\- (\fBdifference_type\fP n, \fBiterator\fP< T > it)\fC [friend]\fP"

.PP
n - it 
.PP
Definition at line 70 of file iterator\&.h\&.
.SS "template<typename T> \fBiterator\fP operator\- (\fBiterator\fP< T > it, \fBdifference_type\fP n)\fC [friend]\fP"

.PP
it - n 
.PP
Definition at line 75 of file iterator\&.h\&.
.SS "template<typename T> std::ostream& operator<< (std::ostream & os, const \fBiterator\fP< T > & v)\fC [friend]\fP"

.PP
<< it 
.PP
Definition at line 86 of file iterator\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Vector from the source code\&.
