.TH "src/main.cpp" 3 "Fri Jul 12 2019" "Version 1.0" "Vector" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/main.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <algorithm>\fP
.br
\fC#include <functional>\fP
.br
\fC#include <iterator>\fP
.br
\fC#include <utility>\fP
.br
\fC#include '\&.\&./include/vector\&.h'\fP
.br
\fC#include 'gtest/gtest\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBTEST\fP (IntVector, DefaultConstructor)"
.br
.ti -1c
.RI "\fBTEST\fP (IntVector, ConstructorSize)"
.br
.ti -1c
.RI "\fBTEST\fP (IntVector, ListConstructor)"
.br
.ti -1c
.RI "\fBTEST\fP (IntVector, RangeConstructor)"
.br
.ti -1c
.RI "\fBTEST\fP (IntVector, CopyConstructor)"
.br
.ti -1c
.RI "\fBTEST\fP (IntVector, MoveConstructor)"
.br
.ti -1c
.RI "\fBTEST\fP (IntVector, AssignOperator)"
.br
.ti -1c
.RI "\fBTEST\fP (IntVector, MoveAssignOperator)"
.br
.ti -1c
.RI "\fBTEST\fP (IntVector, ListInitializerAssign)"
.br
.ti -1c
.RI "\fBTEST\fP (IntVector, Clear)"
.br
.ti -1c
.RI "\fBTEST\fP (IntVector, PushBack)"
.br
.ti -1c
.RI "\fBTEST\fP (IntVector, PopBack)"
.br
.ti -1c
.RI "\fBTEST\fP (IntVector, Front)"
.br
.ti -1c
.RI "\fBTEST\fP (IntVector, FrontConst)"
.br
.ti -1c
.RI "\fBTEST\fP (IntVector, Back)"
.br
.ti -1c
.RI "\fBTEST\fP (IntVector, BackConst)"
.br
.ti -1c
.RI "\fBTEST\fP (IntVector, AssignCountValue)"
.br
.ti -1c
.RI "\fBTEST\fP (IntVector, AssignCountRange)"
.br
.ti -1c
.RI "\fBTEST\fP (IntVector, AssignCountList)"
.br
.ti -1c
.RI "\fBTEST\fP (IntVector, OperatorBracketsRHS)"
.br
.ti -1c
.RI "\fBTEST\fP (IntVector, OperatorBracketsLHS)"
.br
.ti -1c
.RI "\fBTEST\fP (IntVector, AtRHS)"
.br
.ti -1c
.RI "\fBTEST\fP (IntVector, AtLHS)"
.br
.ti -1c
.RI "\fBTEST\fP (IntVector, Capacity)"
.br
.ti -1c
.RI "\fBTEST\fP (IntVector, ShrinkToFit)"
.br
.ti -1c
.RI "\fBTEST\fP (IntVector, OperatorEqual)"
.br
.ti -1c
.RI "\fBTEST\fP (IntVector, OperatorDifferent)"
.br
.ti -1c
.RI "\fBTEST\fP (IntVector, InsertSingleValueAtPosition)"
.br
.ti -1c
.RI "\fBTEST\fP (IntVector, InsertRange)"
.br
.ti -1c
.RI "\fBTEST\fP (IntVector, InsertInitializarList)"
.br
.ti -1c
.RI "\fBTEST\fP (IntVector, AssignCountValue2)"
.br
.ti -1c
.RI "\fBTEST\fP (IntVector, EraseRange)"
.br
.ti -1c
.RI "\fBTEST\fP (IntVector, ErasePos)"
.br
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char ** argv)"

.PP
Definition at line 534 of file main\&.cpp\&.
.SS "TEST (IntVector, DefaultConstructor)"

.PP
Definition at line 11 of file main\&.cpp\&.
.SS "TEST (IntVector, ConstructorSize)"

.PP
Definition at line 19 of file main\&.cpp\&.
.SS "TEST (IntVector, ListConstructor)"

.PP
Definition at line 27 of file main\&.cpp\&.
.SS "TEST (IntVector, RangeConstructor)"

.PP
Definition at line 35 of file main\&.cpp\&.
.SS "TEST (IntVector, CopyConstructor)"

.PP
Definition at line 52 of file main\&.cpp\&.
.SS "TEST (IntVector, MoveConstructor)"

.PP
Definition at line 68 of file main\&.cpp\&.
.SS "TEST (IntVector, AssignOperator)"

.PP
Definition at line 79 of file main\&.cpp\&.
.SS "TEST (IntVector, MoveAssignOperator)"

.PP
Definition at line 92 of file main\&.cpp\&.
.SS "TEST (IntVector, ListInitializerAssign)"

.PP
Definition at line 108 of file main\&.cpp\&.
.SS "TEST (IntVector, Clear)"

.PP
Definition at line 120 of file main\&.cpp\&.
.SS "TEST (IntVector, PushBack)"

.PP
Definition at line 135 of file main\&.cpp\&.
.SS "TEST (IntVector, PopBack)"

.PP
Definition at line 160 of file main\&.cpp\&.
.SS "TEST (IntVector, Front)"

.PP
Definition at line 171 of file main\&.cpp\&.
.SS "TEST (IntVector, FrontConst)"

.PP
Definition at line 187 of file main\&.cpp\&.
.SS "TEST (IntVector, Back)"

.PP
Definition at line 196 of file main\&.cpp\&.
.SS "TEST (IntVector, BackConst)"

.PP
Definition at line 211 of file main\&.cpp\&.
.SS "TEST (IntVector, AssignCountValue)"

.PP
Definition at line 220 of file main\&.cpp\&.
.SS "TEST (IntVector, AssignCountRange)"

.PP
Definition at line 245 of file main\&.cpp\&.
.SS "TEST (IntVector, AssignCountList)"

.PP
Definition at line 260 of file main\&.cpp\&.
.SS "TEST (IntVector, OperatorBracketsRHS)"

.PP
Definition at line 279 of file main\&.cpp\&.
.SS "TEST (IntVector, OperatorBracketsLHS)"

.PP
Definition at line 286 of file main\&.cpp\&.
.SS "TEST (IntVector, AtRHS)"

.PP
Definition at line 294 of file main\&.cpp\&.
.SS "TEST (IntVector, AtLHS)"

.PP
Definition at line 310 of file main\&.cpp\&.
.SS "TEST (IntVector, Capacity)"

.PP
Definition at line 332 of file main\&.cpp\&.
.SS "TEST (IntVector, ShrinkToFit)"

.PP
Definition at line 347 of file main\&.cpp\&.
.SS "TEST (IntVector, OperatorEqual)"

.PP
Definition at line 361 of file main\&.cpp\&.
.SS "TEST (IntVector, OperatorDifferent)"

.PP
Definition at line 373 of file main\&.cpp\&.
.SS "TEST (IntVector, InsertSingleValueAtPosition)"

.PP
Definition at line 385 of file main\&.cpp\&.
.SS "TEST (IntVector, InsertRange)"

.PP
Definition at line 400 of file main\&.cpp\&.
.SS "TEST (IntVector, InsertInitializarList)"

.PP
Definition at line 426 of file main\&.cpp\&.
.SS "TEST (IntVector, AssignCountValue2)"

.PP
Definition at line 452 of file main\&.cpp\&.
.SS "TEST (IntVector, EraseRange)"

.PP
Definition at line 477 of file main\&.cpp\&.
.SS "TEST (IntVector, ErasePos)"

.PP
Definition at line 508 of file main\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Vector from the source code\&.
