.TH "include/vector.h" 3 "Fri Jul 12 2019" "Version 1.0" "Vector" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/vector.h
.SH SYNOPSIS
.br
.PP
\fC#include <algorithm>\fP
.br
\fC#include <cassert>\fP
.br
\fC#include <initializer_list>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <iterator>\fP
.br
\fC#include 'iterator\&.h'\fP
.br
\fC#include 'vector\&.cpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBvector< T >\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor:\fP
.RS 4
Jefferson Bruno, Ranieri Santos 
.RE
.PP
\fBDate:\fP
.RS 4
21/05/2019 
.br
 https://github.com/imns1ght/vector 
.RE
.PP

.PP
Definition in file \fBvector\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Vector from the source code\&.
